INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (-1, 'jdoe', 'John', 'Doe');
INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (-2, 'emuster', 'Erika', 'Mustermann');
INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (-3, 'sdavid', 'Smith', 'David');
INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (-4, 'wtom', 'White', 'Tom');
INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (-5, 'ljohn', 'Lee', 'John');
INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (-6, 'bjack', 'Barrak', 'Jack');